spring:
  application:
    name: stocktracker
  datasource:
    url: "jdbc:h2:file:./data/stocktracker-db"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  cache:
    type: simple

alpha:
  vantage:
    base:
      url: "https://www.alphavantage.co/query"
    api:
      key: "api-key"